name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-streamlit.txt

      - name: Set GitHub Pages environment variable
        run: echo "IS_GITHUB_PAGES=true" >> $GITHUB_ENV

      - name: Verify application structure
        run: |
          ls -la
          python -c "import streamlit; print(f'Streamlit version: {streamlit.__version__}')"
          
      # Note: Actual deployment to Streamlit Cloud happens automatically when 
      # you connect your GitHub repository to your Streamlit Cloud account
      # This workflow just verifies that everything is ready for deployment 